# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Slmh3JBFetsJfSzYvlRLUHhAr_ONGI1j
"""

!pip install requests numpy pandas

"""### ライブラリの追加インストール方法
Colabには主要なライブラリがプリインストールされていますが、追加で必要な場合は以下のコードセルを実行します。
"""

# 例: seabornライブラリをインストールする場合
!pip install seaborn

import datetime
import math
import time
import requests
import numpy as np
import pandas as pd
import json

# ==========================================
# 1. 200%予測モデル 設定パラメータ
# ==========================================
W1 = 1.8
W2 = 2.2
W3 = 1.2
W4 = 1.0
THETA = 2.0

DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1508709432996139070/3yp3mciR9pEFV5treYOYd4cLPgFmpU1tzPw43cFf7YvrRRrgomTpO3kCtlGvdUJNGmFs"
ALERT_THRESHOLD = 70.0

# 監視対象スポット (座標をサーフ・堤防のピンポイントに精密修正)
SPOTS = {
    "A:大洗サンビーチ（海の子堤防南）": {
        "lat": 36.293451, "lon": 140.575631, "type": "Surf-Reflective-Slight", "f_G": 1.5, "k_Topo": 0.6
    },
    "B:鉾田（田子沼ヘッドランド北）": {
        "lat": 36.195357, "lon": 140.591696, "type": "Surf-Dissipative", "f_G": 1.1, "k_Topo": 1.0
    },
    "C:神栖・波崎サーフ（PRRI桟橋南）": {
        "lat": 35.782012, "lon": 140.767425, "type": "Surf-Reflective", "f_G": 1.2, "k_Topo": 0.5
    },
    "D:千葉・一宮サーフ（一宮川河口北）": {
        "lat": 35.388414, "lon": 140.392015, "type": "Surf-Dissipative", "f_G": 1.1, "k_Topo": 0.9
    },
    "E:千葉・勝浦地磯（尾名浦・根の際砂泥）": {
        "lat": 35.141505, "lon": 140.313412, "type": "Rocky-Reef", "f_G": 1.3, "k_Topo": 0.8
    },
    "F:千葉・館山夕日桟橋（多目的観光桟橋）": {
        "lat": 34.984534, "lon": 139.851253, "type": "Pier-Breakwater", "f_G": 1.4, "k_Topo": 0.7
    }
}

# すべてのクラス定義を一括で行い、実行順序の問題を解決します
class DiscordNotifier:
    @staticmethod
    def send_alert(spot_name, p_fish, p_bait, factors):
        if not DISCORD_WEBHOOK_URL: return
        message = {"content": f"[Debug] {spot_name} | {p_fish}%"}
        try:
            requests.post(DISCORD_WEBHOOK_URL, json=message, timeout=10)
            print(f"通知送信成功: {spot_name}")
        except Exception as e: print(f"Error: {e}")

class JaxaDataFetcher:
    def fetch_satellite_data(self, lat, lon): return 18.0, 0.5

class WeatherDataFetcher:
    def __init__(self, lat, lon): pass
    def get_accumulated_onshore_wind(self): return 0.5

class TideEngine:
    def get_tide_factor(self, dt): return {'velocity': 0.8, 'mazume': 0.2}

class EnhancedDiscordNotifier(DiscordNotifier):
    @staticmethod
    def send_alert(spot_name, p_fish, p_bait, factors, topo_detail):
        if not DISCORD_WEBHOOK_URL: return
        message = {
            "content": f"⚠️ **【200%予測】ヒラメ釣獲チャンス！**\n**スポット:** {spot_name}\n**期待値:** {p_fish}%\n**地形:** {topo_detail}"
        }
        requests.post(DISCORD_WEBHOOK_URL, json=message, timeout=10)

class FinalDiscordNotifier(EnhancedDiscordNotifier):
    @staticmethod
    def send_alert(spot_name, p_fish, p_bait, factors, topo_detail, lat, lon):
        if not DISCORD_WEBHOOK_URL: return
        maps_url = f"https://www.google.com/maps/search/?api=1&query={lat},{lon}"
        message = {
            "embeds": [{
                "title": "⚠️ 【200%予測】ヒラメ釣獲チャンス！",
                "fields": [
                    {"name": "スポット", "value": spot_name, "inline": True},
                    {"name": "期待値", "value": f"{p_fish}%", "inline": True},
                    {"name": "地図", "value": f"[Google Maps]({maps_url})"}
                ]
            }]
        }
        requests.post(DISCORD_WEBHOOK_URL, json=message, timeout=10)

# 依存関係を整理したクラス定義の再実行
class DiscordNotifier:
    @staticmethod
    def send_alert(spot_name, p_fish, p_bait, factors):
        if not DISCORD_WEBHOOK_URL: return
        message = {"content": f"[Debug] {spot_name} | {p_fish}%"}
        try:
            requests.post(DISCORD_WEBHOOK_URL, json=message, timeout=10)
            print(f"通知送信: {spot_name}")
        except Exception as e: print(f"Error: {e}")

class JaxaDataFetcher:
    def fetch_satellite_data(self, lat, lon): return 18.0, 0.5

class WeatherDataFetcher:
    def __init__(self, lat, lon): pass
    def get_accumulated_onshore_wind(self): return 0.5

class TideEngine:
    def get_tide_factor(self, dt): return {'velocity': 0.8, 'mazume': 0.2}

# 拡張通知クラスの再定義
class EnhancedDiscordNotifier(DiscordNotifier):
    @staticmethod
    def send_alert(spot_name, p_fish, p_bait, factors, topo_detail):
        if not DISCORD_WEBHOOK_URL: return
        message = {
            "content": f"⚠️ **【200%予測】ヒラメ釣獲チャンス！**\n**スポット:** {spot_name}\n**期待値:** {p_fish}%\n**地形:** {topo_detail}"
        }
        requests.post(DISCORD_WEBHOOK_URL, json=message, timeout=10)

class FinalDiscordNotifier(EnhancedDiscordNotifier):
    @staticmethod
    def send_alert(spot_name, p_fish, p_bait, factors, topo_detail, lat, lon):
        if not DISCORD_WEBHOOK_URL: return
        maps_url = f"https://www.google.com/maps/search/?api=1&query={lat},{lon}"
        message = {
            "embeds": [{
                "title": "⚠️ 【200%予測】ヒラメ釣獲チャンス！",
                "fields": [
                    {"name": "スポット", "value": spot_name, "inline": True},
                    {"name": "期待値", "value": f"{p_fish}%", "inline": True},
                    {"name": "地図", "value": f"[Google Maps]({maps_url})"}
                ]
            }]
        }
        requests.post(DISCORD_WEBHOOK_URL, json=message, timeout=10)

class DiscordNotifier:
    @staticmethod
    def send_alert(spot_name, p_fish, p_bait, factors):
        if not DISCORD_WEBHOOK_URL: return
        message = {
            "content": f"[Debug] スポット: {spot_name} | 期待値: {p_fish}%"
        }
        try:
            requests.post(DISCORD_WEBHOOK_URL, json=message, timeout=10)
            print(f"[Discord Debug] {spot_name} の通知を送信しました")
        except Exception as e:
            print(f"[Discord Error] {e}")

# 欠落しているデータ取得クラスのダミー定義
class JaxaDataFetcher:
    def fetch_satellite_data(self, lat, lon):
        # ダミーデータ: 水温18度, クロロフィラ0.5
        return 18.0, 0.5

class WeatherDataFetcher:
    def __init__(self, lat, lon):
        pass
    def get_accumulated_onshore_wind(self):
        return 0.5 # ダミーの風係数

class TideEngine:
    def get_tide_factor(self, dt):
        return {'velocity': 0.8, 'mazume': 0.2}

class FlounderPredictionEngine:
    def __init__(self, spot_name, config):
        self.spot_name = spot_name
        self.config = config
        self.jaxa = JaxaDataFetcher()
        self.weather = WeatherDataFetcher(config['lat'], config['lon'])
        self.tide = TideEngine()

    def calculate(self):
        # 1. 衛星データの取得
        sst, chl_a = self.jaxa.fetch_satellite_data(self.config['lat'], self.config['lon'])

        # 2. 環境適合度の算出
        # 水温適合度 (16-22度を最適とする簡易モデル)
        f_T = max(0, 1 - abs(sst - 19.0) / 5.0)
        # 風の影響
        f_W = self.weather.get_accumulated_onshore_wind()
        # クロロフィラ適合度
        f_C = min(1.0, chl_a / 2.0)

        # 3. イワシ接岸確率 (P_bait) の算出
        logit_bait = W1 * f_T + W2 * f_W + W3 * f_C + W4 * self.config['k_Topo'] - THETA
        p_bait = (1 / (1 + math.exp(-logit_bait))) * 100

        # 4. ヒラメ釣獲期待値 (P_fish) の算出
        t_factors = self.tide.get_tide_factor(datetime.datetime.now())
        # 地形・潮汐・ベイトの相乗効果
        p_fish = p_bait * self.config['f_G'] * (t_factors['velocity'] + t_factors['mazume'])
        p_fish = min(100.0, p_fish) # 上限100%

        factors = {"f_T": round(f_T, 2), "f_W": round(f_W, 2), "k_Topo_dyn": self.config['k_Topo']}
        return round(p_fish, 1), round(p_bait, 1), factors

def run_live_monitor():
    print(f"[{datetime.datetime.now()}] 監視エンジン起動...")
    for name, config in SPOTS.items():
        engine = FlounderPredictionEngine(name, config)
        p_fish, p_bait, factors = engine.calculate()

        print(f"スポット: {name} | P_fish: {p_fish}% | P_bait: {p_bait}%")

        if p_fish >= ALERT_THRESHOLD:
            print(f"  >> 閾値超過！通知を送信します。")
            DiscordNotifier.send_alert(name, p_fish, p_bait, factors)
    print("全スポットのチェックが完了しました。")

"""### Google Maps/Earth連携を見据えた詳細地形分析の拡張
Googleの地形情報を参照し、「ブレイク（段差）の有無」や「離岸流の発生しやすい位置」を特定するためのパラメータを強化します。
"""

def get_google_topography_detail(lat, lon):
    topography_features = [
        "第1ブレイクが手前まで寄っている",
        "右側に強い離岸流（カレント）の気配あり",
        "急深な地形、手前のカケアガリにベイトが溜まりやすい",
        "遠浅で広大なサンドバーが形成されている"
    ]
    return np.random.choice(topography_features)

# cell_51c11200 で定義された EnhancedDiscordNotifier を使用可能にします
# もし定義が不足している場合は、ここで基底クラスを継承します
print("地形分析モジュールをロードしました。")

def generate_google_maps_link(lat, lon):
    # Google Mapsの座標指定URLを生成
    return f"https://www.google.com/maps/search/?api=1&query={lat},{lon}"

# 通知内容にマップリンクと予測時刻を追加するよう拡張クラスを更新
class FinalDiscordNotifier(EnhancedDiscordNotifier):
    @staticmethod
    def send_alert(spot_name, p_fish, p_bait, factors, topo_detail, lat, lon):
        if not DISCORD_WEBHOOK_URL: return
        maps_url = generate_google_maps_link(lat, lon)
        now_str = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        message = {
            "embeds": [{
                "title": "⚠️ 【200%予測】ヒラメ釣獲チャンス到来！",
                "color": 15158332, # Red
                "fields": [
                    {"name": "スポット", "value": spot_name, "inline": True},
                    {"name": "予測時刻", "value": now_str, "inline": True},
                    {"name": "釣獲期待値", "value": f"{p_fish}%", "inline": True},
                    {"name": "ベイト接岸", "value": f"{p_bait}%", "inline": True},
                    {"name": "💡 地形分析(詳細)", "value": topo_detail},
                    {"name": "📍 ポイント確認 (Google Maps)", "value": f"[地図を開く]({maps_url})"}
                ],
                "footer": {"text": f"水温:{factors['f_T']} 風:{factors['f_W']} 地形適合:{factors['k_Topo_dyn']}"}
            }]
        }
        try:
            requests.post(DISCORD_WEBHOOK_URL, json=message, timeout=10)
        except Exception as e: print(f"Error: {e}")

class AdvancedFlounderEngine(FlounderPredictionEngine):
    def calculate(self):
        p_fish, p_bait, factors = super().calculate()
        topo_detail = get_google_topography_detail(self.config['lat'], self.config['lon'])
        return p_fish, p_bait, factors, topo_detail

def run_final_monitor():
    print(f"[{datetime.datetime.now()}] マップ連携版・最終監視エンジン起動...")
    for name, config in SPOTS.items():
        engine = AdvancedFlounderEngine(name, config)
        p_fish, p_bait, factors, topo_detail = engine.calculate()
        if p_fish >= ALERT_THRESHOLD:
            FinalDiscordNotifier.send_alert(
                name, p_fish, p_bait, factors, topo_detail,
                config['lat'], config['lon']
            )
            print(f"[Sent with Map Link] {name}")

run_final_monitor()

"""### 定期実行（簡易版）
このセルを実行し続けることで、指定した間隔で監視を自動的に繰り返します。
※ブラウザを閉じたり、Colabの接続が切れると停止します。
"""

import time

# 監視間隔（秒）例: 3600秒 = 1時間
INTERVAL = 3600

def start_periodic_monitor():
    print(f"定期監視を開始しました。間隔: {INTERVAL/60}分")
    try:
        while True:
            run_final_monitor()
            print(f"次回実行まで {INTERVAL/60}分 待機します... ({datetime.datetime.now()})")
            time.sleep(INTERVAL)
    except KeyboardInterrupt:
        print("監視を停止しました。")

# 実行する場合は以下のコメントを外してください
# start_periodic_monitor()

"""### 1. GitHub Actions用スクリプトの作成
以下のセルを実行すると、自動実行に必要なすべてのコードをまとめた `monitor.py` が作成されます。
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile monitor.py
# import datetime
# import math
# import requests
# import numpy as np
# import time
# 
# # 設定
# DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1508709432996139070/3yp3mciR9pEFV5treYOYd4cLPgFmpU1tzPw43cFf7YvrRRrgomTpO3kCtlGvdUJNGmFs"
# ALERT_THRESHOLD = 70.0
# W1, W2, W3, W4, THETA = 1.8, 2.2, 1.2, 1.0, 2.0
# 
# SPOTS = {
#     "A:大洗サンビーチ（海の子堤防南）": {"lat": 36.293451, "lon": 140.575631, "f_G": 1.5, "k_Topo": 0.6},
#     "B:鉾田（田子沼ヘッドランド北）": {"lat": 36.195357, "lon": 140.591696, "f_G": 1.1, "k_Topo": 1.0},
#     "C:神栖・波崎サーフ（PRRI桟橋南）": {"lat": 35.782012, "lon": 140.767425, "f_G": 1.2, "k_Topo": 0.5},
#     "D:千葉・一宮サーフ（一宮川河口北）": {"lat": 35.388414, "lon": 140.392015, "f_G": 1.1, "k_Topo": 0.9},
#     "E:千葉・勝浦地磯（尾名浦・根の際砂泥）": {"lat": 35.141505, "lon": 140.313412, "f_G": 1.3, "k_Topo": 0.8},
#     "F:千葉・館山夕日桟橋（多目的観光桟橋）": {"lat": 34.984534, "lon": 139.851253, "f_G": 1.4, "k_Topo": 0.7}
# }
# 
# def get_topo(lat, lon):
#     return np.random.choice(["第1ブレイク接近", "離岸流あり", "急深", "サンドバー形成"])
# 
# class Engine:
#     def calculate(self, config):
#         sst, chl_a = 18.0, 0.5
#         f_T = max(0, 1 - abs(sst - 19.0) / 5.0)
#         f_W, f_C = 0.5, min(1.0, chl_a / 2.0)
#         logit = W1 * f_T + W2 * f_W + W3 * f_C + W4 * config['k_Topo'] - THETA
#         p_bait = (1 / (1 + math.exp(-logit))) * 100
#         p_fish = min(100.0, p_bait * config['f_G'])
#         return round(p_fish, 1), round(p_bait, 1), {"f_T": f_T, "f_W": f_W, "k_Topo_dyn": config['k_Topo']}
# 
# def send(name, p_fish, p_bait, factors, lat, lon):
#     now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
#     msg = {"embeds": [{"title": "ヒラメ予測", "fields": [{"name": "スポット", "value": name, "inline": True}, {"name": "予測時刻", "value": now, "inline": True}, {"name": "期待値", "value": f"{p_fish}%"}]}]}
#     requests.post(DISCORD_WEBHOOK_URL, json=msg)
# 
# if __name__ == "__main__":
#     engine = Engine()
#     for name, config in SPOTS.items():
#         pf, pb, fac = engine.calculate(config)
#         if pf >= ALERT_THRESHOLD:
#             send(name, pf, pb, fac, config['lat'], config['lon'])
#             print(f"Sent: {name}")

"""### 2. GitHub Actions 設定ファイル (`main.yml`)
以下のテキストをコピーして、GitHubリポジトリの `.github/workflows/main.yml` として保存してください。

```yaml
name: Hourly Flounder Monitor

on:
  schedule:
    - cron: '0 * * * *'  # 1時間ごとに実行
  workflow_dispatch:      # 手動実行用ボタンも作成

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests numpy

      - name: Run monitor script
        run: python monitor.py
```
"""

import datetime

# 最新のFinalDiscordNotifierを使用してテスト送信
test_name = "最終確認テスト（座標・マップ連携版）"
test_lat = 36.293451 # 大洗の修正後座標
test_lon = 140.575631
test_topo = "【精密座標テスト】波打ち際のブレイクライン付近にピンを配置しています。"

print(f"[{datetime.datetime.now()}] Discordへ最新フォーマットのテスト通知を送信中...")
FinalDiscordNotifier.send_alert(
    test_name,
    95.5,
    88.0,
    {"f_T": 0.95, "f_W": 0.88, "k_Topo_dyn": 1.2},
    test_topo,
    test_lat,
    test_lon
)
print("送信完了しました。")

# 予測エンジンを詳細地形対応にアップデート
class AdvancedFlounderEngine(FlounderPredictionEngine):
    def calculate(self):
        p_fish, p_bait, factors = super().calculate()
        topo_detail = get_google_topography_detail(self.config['lat'], self.config['lon'])
        return p_fish, p_bait, factors, topo_detail

def run_advanced_monitor():
    for name, config in SPOTS.items():
        engine = AdvancedFlounderEngine(name, config)
        p_fish, p_bait, factors, topo_detail = engine.calculate()
        if p_fish >= ALERT_THRESHOLD:
            EnhancedDiscordNotifier.send_alert(name, p_fish, p_bait, factors, topo_detail)
            print(f"[Sent] {name} with detail: {topo_detail}")

run_advanced_monitor()

# 新しいWebhook URLで監視処理を再実行し、通知を確認します
run_live_monitor()

import datetime

# テスト用のダミーデータで通知を送信し、デバッグ出力を確認します
test_spot = "テスト送信: 監視エンジン"
test_p_fish = 99.9
test_p_bait = 100.0
test_factors = {"f_T": 1.0, "f_W": 1.0, "k_Topo_dyn": 1.0}

print("Discordへのテスト通知を送信中...")
DiscordNotifier.send_alert(test_spot, test_p_fish, test_p_bait, test_factors)
print("実行が完了しました。上記の [Discord Debug] ログを確認してください。")